inhibit_all_warnings!
use_frameworks!

target 'MBoxWorkspaceCore' do
  podspec :subspec => 'Default'
end

target 'MBoxWorkspaceLoader' do
  podspec :subspec => 'Loader'
end

target 'MBoxWorkspace' do
  podspec :subspec => 'Default'
end
