name: Release

on:

  workflow_dispatch:

jobs:
  release:
    runs-on: macos-11
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: "Select Xcode 12.5.1"
        uses: devbotsxyz/xcode-select@v1
        with:
          version: "12.5.1"

      - uses: mboxplus/mbox-build-plugin-action@main
        id: build-plugin
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: mboxplus/mbox-release-plugin-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          build-path: ${{ steps.build-plugin.outputs.build-path }}
          force: true